INSERT INTO Masini 
(Marca,
Model,Categorie,
Poza,Transmisie,
Combustibil,
Aer_conditionat,
Nr_locuri,
Nr_bagaje,
Pret_per_zi,
Status,
ID_Locatie) 
VALUES 
('Opel','Adam','Mici','adam_lrg.jpg','Manuala','Benzina','1','4','2','152','Disponibila','6'),
('Dacia','Logan','Mici','logan_lrg.jpg','Manuala','Benzina','1','5','4','132','Disponibila','7'),
('Volkswagen','Polo','Mici','polo_lrg.jpg','Automata','Electrica','1','5','2','121','Disponibila','8'),
('Volkswagen','Up!','Mici','up_lrg.jpg','Manuala','Benzina','1','4','2','114','Disponibila','9'),
('Toyota','Aygo','Mici','aygo_lrg.jpg','Manuala','Benzina','1','4','2','165','Disponibila','8'),
('Volkswagen','Golf','Medii','golf_lrg.jpg','Manuala','Benzina','1','5','3','151','Disponibila','6'),
('Skoda','Octavia','Medii','octavia_lrg.jpg','Manuala','Motorina','1','5','5','163','Disponibila','7'),
('Dacia','Duster','Medii','duster_lrg.jpg','Manuala','Benzina','1','5','3','122','Disponibila','9'),
('Opel','Mokka','Medii','mokka_lrg.jpg','Manuala','Benzina','1','5','3','122','Disponibila','8'),
('Suzuki','Ateca','Medii','ateca_lrg.jpg','Automata','Benzina','1','5','4','132','Disponibila','9'),
('Peugeot','2008','Medii','2008_lrg.jpg','Automata','Electrica','1','5','4','154','Disponibila','10'),
('Hyundai','Kona','Mari','kona_lrg.jpg','Manuala','Electrica','1','5','3','135','Disponibila','11'),
('Opel','Insignia Estate','Mari','insignia_estate_lrg.jpg','Manuala','Motorina','1','5','4','161','Disponibila','6'),
('Seat','Toledo','Mari','toledo_lrg.jpg','Manuala','Benzina','1','5','5','163','Disponibila','8'),
('Volkswagen','Tiguan','Mari','tiguan_lrg.jpg','Manuala','Benzina','1','5','2','154','Disponibila','6'),
('Seat','Toledo','Mari','toledo_lrg.jpg','Manuala','Motorina','1','5','5','163','Disponibila','7'),
('Skoda','Superb','Mari','superb_lrg.jpg','Manuala','Motorina','1','5','5','174','Disponibila','9'),
('BMW','Seria 5','Premium','5_series_lrg.jpg','Automata','Motorina','1','5','5','255','Disponibila','11'),
('Audi','A4','Premium','a4_lrg.jpg','Automata','Motorina','1','5','5','262','Disponibila','10'),
('Audi','Q5','Premium','q5_lrg.jpg','Automata','Motorina','1','5','5','371','Disponibila','7'),
('BMW','Seria 5','Premium','5_series_lrg.jpg','Automata','Motorina','1','5','5','255','Disponibila','9'),
('Mercedes-Benz','E-Class','Premium','e_class_lrg.jpg','Automata','Motorina','1','5','5','361','Disponibila','8'),
('Mercedes-Benz','ML','Premium','ml_class_lrg.jpg','Automata','Motorina','1','5','5','373','Disponibila','6'),
('Dacia','Lodgy','Monovolum','lodgy_lrg.jpg','Manuala','Motorina','1','7','5','411','Disponibila','7'),
('Mercedes','Vito','Monovolum','vito_lrg.jpg','Automata','Motorina','1','7','5','471','Disponibila','8'),
('Peugeot','Vivaro','Monovolum','vivaro_lrg.jpg','Manuala','Motorina','1','10','5','511','Disponibila','9');

